bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('<int:rubric_pk>/<int:pk>', views.detail, name='detail'),
    path('<int:pk>', views.by_rubric, name='by_rubric'),
    path('<str:page>', views.other_page, name='other'),
    path('accounts/login', views.BBLoginView.as_view(), name='login'),
    path('accounts/logout', views.BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change', views.ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change', views.BBPasswordChangeView.as_view(), name='password_change'),
    #path('accounts/profile/<int:pk>', views.profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile', views.profile, name='profile'),
    path('accounts/register/done/', views.RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    path('', views.index, name='index'),

    ]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification
from .utilities import get_timestamp_path

# Create your models here.

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошёл активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        pass


#  user_registrated= Signal(providing_args=['instance'])
#
# def user_registrated_dispatcher(sender, **kwargs):
#     send_activation_notification(kwargs['instance'])
#
#
# user_registrated.connect(user_registrated_dispatcher)




class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Название')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Надрубрика')


class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SuperRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name',)
        verbose_name = 'Надрубрика'
        verbose_name_plural = 'Надрубрики'


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)

class SubRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return '{}-{}'.format(self.super_rubric, self.name)

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name',)
        verbose_name = 'Подрубрика'
        verbose_name_plural = 'Подрубрики'


class Bb(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='рубрика')
    title = models.CharField(max_length=40, verbose_name='Товар')
    content = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0, verbose_name='Цена')
    contacts = models.TextField(verbose_name='Контакты')
    image = models.ImageField(upload_to=get_timestamp_path, blank=True, verbose_name='Изображения')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор обьвления')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить всписке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural ='Обьявления'
        verbose_name = 'Обьявление'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='Обьявление')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

main/forms.py
from django import forms
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import SuperRubric, SubRubric

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages',)


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес злектронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль повторно', widget=forms.PasswordInput, help_text='Введите тот же самый пароль для проверки')

    def clean_password(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введённые пароли не совпадают', code='password_mismatch')}
            raise ValidationError

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        #user_registrated.send(RegisterUserForm, instance=user )
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages',)


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None, label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.template.loader import get_template
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from .models import AdvUser
from .forms import ChangeUserInfoForm, RegisterUserForm
from django.core.paginator import Paginator
from django.db.models import Q
from .models import SubRubric, Bb
from .forms import SearchForm


# Create your views here.

def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form}
    return render(request, 'main/by_rubric.html', context)



def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)

templates/main/about.html
{% extends 'layot/basic.html' %}
{% block title %}
О сайте
{% endblock %}
{% block content %}
<h2>О сайте</h2>
    <p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</p>
    <p>Все права принадлежат читателям книги &quot;Django 2.l&quot;.</p>
{% endblock %}

templates/main/by_rubric.html
{% extends 'layot/basic.html' %}
{% load static %}
{% load thumbnail %}
{% load bootstrap4 %}
{% block title %}
{{ rubric }}
{% endblock %}
{% block searchform %}

{% endblock %}
{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
    <div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Искать' button_type='submit' %}
        </form>
    </div>
    </div>
    {% if bbs %}
    <ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
                <img src="{% thumbnail bb.image 'default' %}" alt="" class="mr-3">
                {% else %}
                <img src="{% static 'main/empty.jpg' %}" alt="" class="mr-3">
            {% endif %}
        </a>
    <div class="media-body">
        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
        <div>{{ bb.content }}</div>
        <p class="text-right font-weight-bold">{{ bb.price }} rub.</p>
        <p class="text-right font-italic">{{ bb.created_at }}</p>
    </div>
    </li>
    {% endfor %}

    </ul>
        {% bootstrap_pagination page url=keyword %}
    {% endif %}
{% endblock %}

templates/main/change_user_info.html
{% extends 'layot/basic.html' %}
{% load bootstrap4 %}
{% block title %}
Правка личных данных
{% endblock %}
{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/detail.html
{% extends 'layot/basic.html' %}
{% block title %}
{{ bb.title }} - {{ bb.rubric.name }}
{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
<div class="row">
    {% if bb.image %}
    <div class="col-md-auto">
        <img src="{{ bb.image.url }}" class="main-image">
    </div>
    {% endif %}
<div class="col">
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p class="font-weight-bold">{{ bb.price }} rub</p>
    <p>{{ bb.contacts }}</p>
    <p class="text-right font-italic">Обьявлени добавлено {{ bb.created_at }}</p>
</div>
</div>
</div>
    {% if ais %}
    <div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img src="{{ ai.image.url }}" alt="" class="additional-image">
    </div>
    {% endfor %}
    
    </div>
    {% endif %}
    <p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Назад</a></p>
{% endblock %}

templates/main/index.html
{% extends 'layot/basic.html' %}
{% block content %}
<h2>Последние 10 обьявлений</h2>
{% endblock %}

templates/main/login.html
{% extends 'layot/basic.html' %}
{% load bootstrap4 %}
{% block title %}
Вход
{% endblock %}
{% block content %}
<h2>Вход</h2>
    {% if user.is_authenticated %}
    <p>Вы уже выполнили вход</p>
        {% else %}
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layot='horizontal' %}
            <input type="hidden" name="text" value="{{ next }}">
        {% buttons submit='Войти' %}{% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

templates/main/logout.html
{% extends 'layot/basic.html' %}
{% block title %}
Выход
{% endblock %}
{% block content %}
<h2>Выход</h2>
    <p>Вы успешно вышли с сайта</p>
{% endblock %}

templates/main/password_change.html
{% extends 'layot/basic.html' %}
{% load bootstrap4 %}
{% block title %}
Смена пароля
{% endblock %}
{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %}{% endbuttons %}
    </form>
{% endblock %}

templates/main/profile.html
{% extends 'layot/basic.html' %}
{% block title %}
Профиль пользователя
{% endblock %}
{% block content %}
<h2>Профиль пользователя</h2>
    {% if user.first_name and user.last_name %}
    <p>Здравствуйте {{ user.first_name }} {{ user.last_name }}!</p>
        {% else %}
        <p>Здравствуйте</p>

    {% endif %}
    <p>Ващи обьявления</p>
{% endblock %}

templates/main/register_done.html
{% extends 'layot/basic.html' %}

{% block title %}
Регистрация завершена
{% endblock %}
{% block content %}
<h2>Регистрация пользователя завершена</h2>
   <p>На адрес
электронной почты,
указанный пользователем,
выслано nисьмо
для активации.</p>
{% endblock %}

templates/main/register_user.html
{% extends 'layot/basic.html' %}
{% load bootstrap4 %}
{% block title %}
Регистрация
{% endblock %}
{% block content %}
<h2>Регистрация нового пользователя</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
    </form>
{% endblock %}