bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('<int:rubric_pk>/<int:pk>', views.detail, name='detail'),
    path('<int:pk>', views.by_rubric, name='by_rubric'),
    path('<str:page>', views.other_page, name='other'),
    path('accounts/login', views.BBLoginView.as_view(), name='login'),
    path('accounts/logout', views.BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change', views.ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change', views.BBPasswordChangeView.as_view(), name='password_change'),
    #path('accounts/profile/<int:pk>', views.profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile', views.profile, name='profile'),
    path('accounts/register/done/', views.RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    path('', views.index, name='index'),

    ]

templates/layot/basic.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type"
          content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=l, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Дос ка объявлений</title>


    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<div class="container">
    <body class="container-fluid">
    <header class="mЬ-4">
        <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a class="nav-link" href="{% url 'main:register' %}">Регистрация</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">Профиль</a>


                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Moи
                            объявления
                        </a>
                        <a
                                class="dropdown-item"
                                href="{% url 'main:profile_change' %}">Изменить личные
                            данные
                        </a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>


                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Удалить</a>

                    </div>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Bxoд</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a href="{% url 'main:other' page='about' %}">О сайте</a>
            <a class="nav-link root"
               href="{% url 'main:index' %}">Главная
            </a>
            {% for rubric in rubrics %}
            {% ifchanged rubric.super_rubric.pk %}
            <span class="nav-link root font-weight-bold">{{ rubric.super_rubric.name }}</span>
            {% endifchanged %}
                <a class="nav-link" href="{% url 'main:by_rubric' pk=rubric.pk %}">{{ rubric.name }}</a>
            {% endfor %}

            <span class="nav-link root font-weight-bold">Недвижимость</span>

            <a class="nav-link" href="#">Жилье</a>
            <a class="nav-link" href="#">Склады</a>
            <a class="nav-link" href="#">Гаражи</a>
            <span class="nav-link root font-weight-bold" href="#">Транспорт</span>
            <a href="#">Легковой</a>
            <a href="#">Грузовой</a>


        </nav>
        <section class="col border ру-2">
            {% bootstrap_messages %}
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy;2020 г.</p>

    </footer>
    </body>
</div>
</html>